player-joined= "&aThe player %s &a joined the server!"
welcome-player= "&eWelcome to server %s!"
welcome-to= "&7Welcome to"

no-link-yet= "&cThis link has not been established!"

visit= "&fVisit our %s &fpage &o&a%s"

store= "&dVisit our store and get stuff to look cooler! &o&b%s"

returned-to-lobby= "&7You're back in the lobby!"

server-rules-head= "SERVER RULES"
server-rules-body= "1) Example one. 2) Example two."

in-stream= "&7ยก&d%s &7 is in stream! &r%s"

report-a-player= "REPORT A PLAYER"
report-cancelled= "&cYour report was cancelled!"
report= "REPORT A %s"
confirm-report= "CONFIRM YOUR REPORT"
reported= "Reported"
player-reported= "&c[!] %s&7 reported to &c%s&7 for &e'%s'"
report-success= "&aYour report was sent successfully!"
no-players-to-report= "&cThere are no players to report!"

reason= "Reason"
your-reason-here= "Type the reason here"
enter-a-valid-reason= "&cPlease enter a valid reason!"

player-offline= "&cPlayer %s is not online!"

usage= "&cUsage: %s"
