no-link-yet= "&c¡Este enlace no se ha establecido!"

visit= "&fVisita nuestra página %s &f &o&a%s"

store= "&d¡Visita nuestra tienda y consigue cosas para estar más guay! &o&b%s"

returned-to-lobby= "&7¡Has vuelto al vestíbulo!"

server-info-head= "INFO DEL SERVIDOR"
server-info-body= ""

rules= "Reglas"
server-rules-head= "REGLAS DEL SERVIDOR"
server-rules-body= "1) Ejemplo uno. 2) Ejemplo dos."

ranks= "Rangos"
server-ranks-head= "RANGOS DEL SERVIDOR"
server-ranks-body= "1) Ejemplo uno. 2) Ejemplo dos."

in-stream= "&7¡&d%s &7está en stream! &r%s"

report-a-player= "REPORTAR UN JUGADOR"
report-cancelled= "&c¡Su informe ha sido cancelado!"
report= "REPORT A %s"
confirm-report= "CONFIRMA TU INFORME"
reported= "Informado"
player-reported= "&c[!] %s&7 reportado &c%s&7 para &e'%s'"
report-success= "&a¡Tu informe se ha enviado correctamente!"
no-players-to-report= "&c¡No hay jugadores para reportar!"
cant-report-yourself= "&cNo puedes reportarte a ti mismo"

reason= "Razón"
your-reason-here= "Escribe aquí el motivo"
enter-a-valid-reason= "&cPor favor, introduce una razón válida!"

player-offline= "&c¡El jugador %s no está conectado!"

usage= "&cUso: %s"

accept= "ACEPTAR"
cancel= "CANCELAR"

un-nicked= "&cHas sido un-nick (%s -> %s)"
nicked= "&aLe han hecho un nick (%s -> %s)"

afk= "&cHas sido expulsado del servidor por inactividad"

un-skin= "&cTu skin ha sido eliminado"
searching-skin= "&aEstamos buscando el skin %s"
searching-random-skin= "&aEstamos buscando una skin aleatoria"
skin-failed= "&cPiel no encontrada"
skin= "&a¡Se ha puesto el nuevo skin!"

coming-soon= "&cPróximamente"
new= "&l&b¡NUEVO!"

navigator= "NAVEGADOR"

use-in-lobby= "&cUsa esto en el vestíbulo"

fly-enabled= "&aVolar activado"
fly-disabled= "&cVolar desactivado"
