no-link-yet= "&cThis link has not been established!"

visit= "&fVisit our %s &fpage &o&a%s"

store= "&dVisit our store and get stuff to look cooler! &o&b%s"

returned-to-lobby= "&7You're back in the lobby!"

server-info-head= "SERVER INFO"
server-info-body= ""

rules= "Rules"
server-rules-head= "SERVER RULES"
server-rules-body= "1) Example one. 2) Example two."

ranks= "Ranks"
server-ranks-head= "SERVER RANKS"
server-ranks-body= "1) Example one. 2) Example two."

in-stream= "&7ยก&d%s &7is in stream! &r%s"

report-a-player= "REPORT A PLAYER"
report-cancelled= "&cYour report was cancelled!"
report= "REPORT A %s"
confirm-report= "CONFIRM YOUR REPORT"
reported= "Reported"
player-reported= "&c[!] %s&7 reported &c%s&7 for &e'%s'"
report-success= "&aYour report was sent successfully!"
no-players-to-report= "&cThere are no players to report!"
cant-report-yourself= "&cYou can't report yourself"

reason= "Reason"
your-reason-here= "Type the reason here"
enter-a-valid-reason= "&cPlease enter a valid reason!"

player-offline= "&cPlayer %s is not online!"

usage= "&cUsage: %s"

accept= "ACCEPT"
cancel= "CANCEL"

un-nicked= "&cYou have been un-nicked (%s -> %s)"
nicked= "&aYou have been nicked (%s -> %s)"

afk= "&cYou have been kicked from the server for inactivity"

un-skin= "&cYour skin has been removed"
searching-skin= "&aWe are looking for the %s skin"
searching-random-skin= "&aWe are looking for a random skin"
skin-failed= "&cSkin not found"
skin= "&aThe new skin was put on!"

coming-soon= "&cComing Soon"
new= "&l&bNEW!"

navigator= "NAVIGATOR"

use-in-lobby= "&cUse this in lobby"

fly-enabled= "&aFly enabled"
fly-disabled= "&cFly disabled"

queued= "&bYou have queued for &6%s"
player-join= "&a> %s&r &7joined the queue!"
player-left= "&c> %s&r &7came out of the queue!"
queue-info= "&6Queued for &b%s &f(%s%s/%s&r) &f[%s&r | &7%s&r]"
removed-previous-queue= "&cYou have been removed from your previous queue!"
error-searching-queue= "&cError looking for a queue!"
no-queue-found= "&cNo queue found with that access code!"
private= "PRIVATE"
public= "PUBLIC"
already-in-queue= "&cYou are already in a queue for that game!"
no-in-queue= "&cYou are not in queue!"
left-queue= "&cYou left the queue"
game-no-exist= "&cThat kind of game doesn't exist!"
you-create-queue= "&aYou created a new queue, type /queue %s in chat to join!"
already-in-this-queue= "&cYou are aldready in this queue!"
