refilling = "&aRefilling chests"
refill-in = "&cRefill in: &f%s"
players-left = "&bPlayers left: &f%s"
airdrops-falling = "&bThe airdrops are falling!"
you-must-wait = "&cYou must wait to throw a new TNT"
