refilling = "&aRellenando cofres"
refill-in = "&cRellenando en: &f%s"
players-left = "&bJugadores vivos: &f%s"
airdrops-falling = "&bLos airdrops estan cayendo!"
you-must-wait = "&cYou must wait to throw a new TNT"
