opponent = "&bOponente: &f%s"
player-goal = "¡%s &ha marcado un puntol!"
no-players-to-duel = "&c¡No hay jugadores para el duelo!"
challenge-player = "DESAFÍA A UN JUGADOR"
duel-no-exist = "&c¡La solicitud de duelo no existe!"
duel-expired = "&c¡El duelo para %s expiró!"
retado-un-jugador = "&aHas desafiado a %s&r&a a &6%s"
player-challenged-you = "%s&r &achallenged te ha desafiado &6%s%n&7escribe /duel accept para mostrar la lista de valores por defecto o /duel accept %s"
duel-requests = "SOLICITUDES DE DUELO"
already-sent-duel = "&c¡Ya has enviado un duelo a ese jugador!"
duel-menu = "MENÚ DE DUELO"
requests = "Peticiones"
send-duel = "Enviar duelo"
