opponent = "&bOponente: &f%s"
player-goal = "¡%s &fha marcado un punto!"
no-players-to-duel = "&c¡No hay jugadores para un duelo!"
challenge-player = "DESAFÍA A UN JUGADOR"
duel-no-exist = "&c¡La solicitud de duelo no existe!"
duel-expired = "&c¡El duelo para %s expiró!"
challenged-a-player = "&aHas desafiado a %s&r&a a &6%s"
player-challenged-you = "%s&r &ate ha desafiado a &6%s%n&7escribe /duel accept para mostrar tu lista de solicitudes para duelos o /duel accept %s"
duel-requests = "SOLICITUDES DE DUELO"
already-sent-duel = "&c¡Ya has enviado un duelo a ese jugador!"
duel-menu = "MENÚ DE DUELO"
requests = "Peticiones"
send-duel = "Enviar duelo"
