opponent= "&bOpponent: &f%s"
player-goal= "%s &escored a goal!"
no-players-to-duel= "&cThere are no players to duel!"
challenge-player= "CHALLENGE A PLAYER"
duel-no-exist= "&cThe duel request does not exit!"
duel-expired= "&cThe duel for %s expired!"
challenged-a-player= "&aYou challenged %s&r&a to &6%s"
player-challenged-you= "%s&r &achallenged you to &6%s%n&7type /duel accept to display the list of defaults or /duel accept %s"
duel-requests= "DUEL REQUESTS"
already-sent-duel= "&cYou already sent a duel to that player!"
duel-menu= "DUEL MENU"
requests= "Requests"
send-duel= "Send duel"
