oponente = "&bOponente: &f%s"
jugador-gol = "¡%s &ha marcado un puntol!"
no-players-to-duel = "&c¡No hay jugadores para el duelo!"
desafiar-jugador = "DESAFÍA A UN JUGADOR"
duelo-no-existe = "&c¡La solicitud de duelo no existe!"
duelo-expirado = "&c¡El duelo para %s expiró!"
retado-un-jugador = "&aHas desafiado a %s&r&a a &6%s"
player-challenged-you = "%s&r &achallenged te ha desafiado &6%s%n&7escribe /duel accept para mostrar la lista de valores por defecto o /duel accept %s"
duel-requests = "SOLICITUDES DE DUELO"
ya-enviado-duelo = "&c¡Ya has enviado un duelo a ese jugador!"
duel-menu = "MENÚ DE DUELO"
peticiones = "Peticiones"
enviar-duelo = "Enviar duelo"
