queued = "&bYou have queued for &6%s"
queue-join = "&a> %s&r &7joined the queue!"
queue-left = "&c> %s&r &7left the queue!"
queue-info = "&6Queued for &b%s &f(%s%s/%s&r) &f[%s&r | &7%s&r]"
removed-previous-queue = "&cYou have been removed from your previous queue!"
error-searching-queue = "&cError looking for a queue!"
no-queue-found = "&cNo queue found with that access code!"
private = "PRIVATE"
public = "PUBLIC"
already-in-queue = "&cYou are already in a queue for that game!"
no-in-queue = "&cYou are not in queue!"
left-queue = "&cYou left the queue"
game-no-exist = "&cThat kind of game doesn't exist!"
you-create-queue = "&aYou created a new queue, type /queue %s in chat to join!"
already-in-this-queue = "&cYou are aldready in this queue!"
no-enough-players = "&4Not enough players to start"
queue-start-in = "&aThe game will start in %s &aseconds!"
go = "&l&bGo!"
game-started-good-luck = "&o&7The game has started, good luck!"
random = "RANDOM"
there-no-maps = "&cQueue has been removed due to no maps!"
map-winner-header = "&a%s Map"
map-winner-footer = "&7By %s"
generating-map = "&dGenerating map"

seconds-to-end = "&cThe game will be over in %s seconds!"

map-vote-closed = "&cMap voting is over!"
already-vote = "&cYou already voted!"
map-vote-success = "&aYou voted for map &7%s"
map-vote = "MAP VOTE"

won-game = "%s &r&awon the game!"

forced-start = "%s &r&bforced the start of the game!"
queue-already-starting = "&cThis queue is already starting!"
game-over-header = "&l&6GAME OVER"
you-died-footer = "&7You died"
no-winners-footer = "&7No winners"
you-assisted = "&eYou assisted to kill %s"
killed-by = "&e%s &cwas killed by &e%s"
died = "&e%s &cdied"

map = "&cMap: &f%s"
ends-in = "&cEnds in: &f%s"
kills = "&6Kills: &f%s"

follow-a-player = "FOLLOW A PLAYER"
cant-follow-yourself = "&cYou can't follow yourself"
match-list = "MATCH LIST"

game-npc-placed = "&aYou have placed the npc"
game-npc-deleted = "&cYou have removed the npc"

match-join = "&a> %s&r &fjoined &7(%s/%s)&f!"
match-left = "&c> %s&r &fleft &7(%s/%s)&f!"

error-creating-match = "&cError creating match. Try againg!"
match-access-code = "&aYou entered a static game!. The access code is: %s"
game-mode = "SELECT GAME MODE"
map-no-exist = "&cThis map ceased to exist!"

you-are-in-queue = "&cYou are already in a queue!"

user-in-pvp = "&c%s is in pvp with %s!. You have to wait if you want a pvp with him"
you-are-in-pvp = "&cYou are in pvp with %s!. You have to wait if you want a pvp with him"