queued = "&bHas hecho cola para &6%s"
queue-join = "&a> %s&r &7se ha unido a la partida!"
queue-left = "&c> %s&r &7abandonó la partida!"
queue-info = "&6En cola para &b%s &f(%s%s/%s&r) &f[%s&r | &7%s&r]"
removed-previous-queue = "&c¡Ha sido eliminado de la partida anterior!"
error-searching-queue = "&c¡Error al buscar una partida!"
no-queue-found = "&c¡No se ha encontrado ninguna partida con ese código de acceso!"
private = "PRIVADO"
public = "PÚBLICO"
already-in-queue = "&cYa estás en una cola para ese juego!"
no-in-queue = "&c¡No estás en la cola!"
left-queue = "&c¡Has abandonado la cola!"
game-no-exist = "&c¡Ese tipo de juego no existe!"
you-create-queue = "&a¡Has creado una nueva partida, escribe /queue %s en el chat para unirte!"
already-in-this-queue = "&cYa estás en esta cola!"
no-enough-players = "&4No hay suficientes jugadores para empezar"
queue-start-in = "&aLa partida empezará en %s &asegundos!"
go = "&l&b¡Vamos!"
game-started-good-luck = "&o&7El juego ha comenzado, ¡buena suerte!"
random = "RANDOM"
there-no-maps = "&c¡Se ha eliminado la partida por falta de mapas!"
map-winner-header = "&a%s Mapa"
map-winner-footer = "&7Por %s"
generating-map = "&dGenerando mapa"

seconds-to-end = "&c¡El juego terminará en %s segundos!"

map-vote-closed = "&c¡La votación del mapa ha terminado!"
already-vote = "&cYa has votado!"
map-vote-success = "&aHas votado por el mapa &7%s"
map-vote = "VOTA POR UN MAPA"

won-game = "%s &r&aganó la partida!"

forced-start = "&b¡%s &r&bforzó el inicio de la partida!"
queue-already-starting = "&c¡Esta cola ya está empezando!"
game-over-header = "&l&6JUEGO TERMINADO"
you-died-footer = "&7Has muerto"
no-winners-footer = "&7Sin ganadores"
you-assisted = "&eHas ayudado a matar a %s"
killed-by = "&e%s &cfue asesinado por &e%s"
died = "&e%s &cmurio"

map = "&cMapa: &f%s"
ends-in = "&cFinaliza en: &f%s"
kills = "&6Asesinatos: &f%s"

follow-a-player = "SEGUIR A UN JUGADOR"
cant-follow-yourself = "&cNo puedes seguirte a ti mismo"
match-list = "LISTA DE PARTIDAS"

game-npc-placed = "&aHas colocado el npc"
game-npc-deleted = "&cYou have removed the npc"

match-join = "&a> %s&r &fse ha unido &7(%s/%s)&f!"
match-left = "&c> %s&r &fse ha ido &7(%s/%s)&f!"

error-creating-match = "&cError al crear la partida. Intentalo de nuevo!"
match-access-code = "&a¡Ha entrado en una partida! El código de acceso es: %s"
game-mode = "SELECCIONAR MODO DE JUEGO"
map-no-exist = "&c¡Este mapa ha dejado de existir!"

you-are-in-queue = "&cYou are already in a queue!"