player-joined= "&8[&a+&8] &c%s &r&ajoined the server!"
welcome-player= "&bWelcome to &6&lOlcano &r&b%s!%n&c&lRespect the rules and follow us on our social networks :)%n&dTikTok: @OlcanoMC%n&bTwitter: @OlcanoMC%n&cYouTube: @Olcano%n&9Discord: https://discord.gg/BwZwwKq"
welcome-to= "&aWelcome"

you-are-nicked= "&cYOU ARE NICKED"

name= "Name: &c %s"
rank= "Rank: &6 %s"
online= "Online: &a %s"
