player-joined= "&8[&a+&8] &6%s &r&ajoined the server!"
welcome-player= "------------------------------------------------%n&bWelcome to &6&lOlcano &r&b%s!%n&c&lRespect the rules and follow us on our social networks :)%n%n&r&dTikTok: @OlcanoMC%n&r&bTwitter: @OlcanoMC%n&r&cYouTube: @Olcano%n&r&9Discord: https://discord.gg/BwZwwKq%n------------------------------------------------"
welcome-to= "&aWelcome"

you-are-nicked= "&cYOU ARE NICKED"

name= "Name: %s"
rank= "Rank: %s"
online= "Online: %s"
