player-joined = "%s &r&ajoined the server!."
welcome-player = "&eWelcome to server %s!"
welcome-to = "&fWelcome to %s"

you-are-nicked = "&cYOU ARE NICKED"

name = "Name: %s"
rank = "Rank: %s"
online = "Online: &a%s"
