player-joined= "&a¡&r&8[&a+&8] &c%s &r&ase ha unido al servidor!"
welcome-player= "&bBienvenido a &6&lOlcano &r&b%s!%n&c&lRespeta las normas y síguenos en nuestras redes sociales :)%n%n&r&dTikTok: @OlcanoMC%n&r&bTwitter: @OlcanoMC%n&r&cYouTube: @Olcano%n&r&9Discord: https://discord.gg/BwZwwKq"
welcome-to= "&fBienvenido a %s"

you-are-nicked= "&cNick cambiado"

name= "Nombre: %s"
rank= "Rango: %s"
online= "En línea: %s"
