player-joined= "&r&8[&a+&8] &6%s &r&ase ha unido al servidor!"
welcome-player= "&3------------------------------------------------%n&&bBienvenido a &6&lOlcano &r&b%s!%n&c&lRespeta las normas y síguenos en nuestras redes sociales :)%n%n&r&dTikTok: @OlcanoMC%n&r&bTwitter: @OlcanoMC%n&r&cYouTube: @Olcano%n&r&9Discord: https://discord.gg/BwZwwKq%n&3------------------------------------------------"
welcome-to= "&fBienvenido a%n %s"

you-are-nicked= "&cNick cambiado"

name= "Nombre: %s"
rank= "Rango: %s"
online= "En línea: %s"
