player-joined= "¡%s &r&se ha unido al servidor!"
welcome-player= "&e¡Bienvenido al servidor %s!"
welcome-to= "&fBienvenido a %s"

you-are-nicked= "&cNick cambiado"

name= "Nombre: %s"
rank= "Rango: %s"
online= "En línea: &a%s"
